replicaCount: 1

image:
  repository: moussaba78/app-moussaba-exam
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: moussaba.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
