apiVersion: v1
kind: Service
metadata:
  name: gateway-nodeport
  namespace: qa
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
